-- Create service_requests table to track multiple alerts per table
create table if not exists public.service_requests (
    id bigint generated by default as identity primary key,
    table_id bigint references public.tables(id) on delete cascade not null,
    request_type text not null, -- 'water_requested', 'bill_requested', etc.
    status text not null default 'pending', -- 'pending', 'resolved'
    created_at timestamptz default now() not null,
    resolved_at timestamptz
);

-- Add simple RLS policies
alter table public.service_requests enable row level security;

create policy "Enable read access for all users" on public.service_requests
    for select using (true);

create policy "Enable insert access for all users" on public.service_requests
    for insert with check (true);

create policy "Enable update access for all users" on public.service_requests
    for update using (true);

-- Enable Realtime
alter publication supabase_realtime add table public.service_requests;
