// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/(auth)/login/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/admin">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/kds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/kds">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/kds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/mfa-setup/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/mfa-setup">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/mfa-setup/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/login/waiter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login/waiter">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/login/waiter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/(auth)/waiting-approval/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/waiting-approval">> = Specific
  const handler = {} as typeof import("../../../app/(auth)/waiting-approval/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/about">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/analytics">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/areas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/areas">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/areas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/customers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/customers">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/customers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/history/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/history">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/history/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/homepage-builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/homepage-builder">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/homepage-builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/inventory/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/inventory/alerts">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/inventory/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/inventory/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/inventory/calendar">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/inventory/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/inventory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/inventory">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/inventory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/inventory/recipes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/inventory/recipes">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/inventory/recipes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/live-kitchen/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/live-kitchen">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/live-kitchen/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/menu/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/menu">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/menu/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/offers">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/orders">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/security">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/services/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/services">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/services/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/settings">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/specials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/specials">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/specials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/staff/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/staff">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/staff/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/tables/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/admin/tables">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/tables/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/cart/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/cart/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/cart/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/combos/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/combos/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/combos/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/home/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/home/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/home/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/menu/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/menu/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/menu/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/myorders/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/myorders/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/myorders/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/offers/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/offers/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/offers/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/service/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/service/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/service/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/services/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/services/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/services/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/specials/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/specials/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/specials/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/status/[tableNumber]/[orderId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/status/[tableNumber]/[orderId]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/status/[tableNumber]/[orderId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/table/[tableNumber]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/customer/table/[tableNumber]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/table/[tableNumber]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/kds/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/kds">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/kds/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/portal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/portal">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/portal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/staff/[staffMobile]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/staff/[staffMobile]/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/staff/[staffMobile]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/supervisor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/supervisor">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/supervisor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/waiter/[staffMobile]/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/waiter/[staffMobile]/alerts">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/waiter/[staffMobile]/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/waiter/[staffMobile]/cart/[tableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/waiter/[staffMobile]/cart/[tableId]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/waiter/[staffMobile]/cart/[tableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/waiter/[staffMobile]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/waiter/[staffMobile]/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/waiter/[staffMobile]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/waiter/[staffMobile]/menu/[tableId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/waiter/[staffMobile]/menu/[tableId]">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/waiter/[staffMobile]/menu/[tableId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/waiter/[staffMobile]/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/waiter/[staffMobile]/profile">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/waiter/[staffMobile]/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/waiter/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/[restaurantCode]/waiter/login">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/waiter/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/activation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/activation">> = Specific
  const handler = {} as typeof import("../../../app/activation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/activate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/activate">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/activate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/complete-mfa-reset/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/complete-mfa-reset">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/complete-mfa-reset/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/employee/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/employee/approve">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/employee/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/employee/change-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/employee/change-email">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/employee/change-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/employee/create/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/employee/create">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/employee/create/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/employee/verify-email/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/employee/verify-email">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/employee/verify-email/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/owner/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/owner/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/owner/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner/send-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/owner/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/owner/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner/status">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/owner/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/owner/submit-restaurant/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner/submit-restaurant">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/owner/submit-restaurant/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/owner/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/owner/verify-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/owner/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/security/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/security/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/security/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/session/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/session">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/session/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/sessions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/sessions">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/sessions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/waiter/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/waiter/login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/waiter/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/waiter/mobile-login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/waiter/mobile-login">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/waiter/mobile-login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/waiter/send-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/waiter/send-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/waiter/send-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/waiter/verify-otp/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/waiter/verify-otp">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/waiter/verify-otp/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/backup/cron/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/backup/cron">> = Specific
  const handler = {} as typeof import("../../../app/api/backup/cron/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/lookup-phone/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/lookup-phone">> = Specific
  const handler = {} as typeof import("../../../app/api/lookup-phone/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/media/private/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/media/private">> = Specific
  const handler = {} as typeof import("../../../app/api/media/private/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/monitor/log/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/monitor/log">> = Specific
  const handler = {} as typeof import("../../../app/api/monitor/log/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/restaurant/[restaurantCode]/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/restaurant/[restaurantCode]/plan">> = Specific
  const handler = {} as typeof import("../../../app/api/restaurant/[restaurantCode]/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/super-admin/restaurants/[id]/plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/super-admin/restaurants/[id]/plan">> = Specific
  const handler = {} as typeof import("../../../app/api/super-admin/restaurants/[id]/plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/super-admin/restaurants/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/super-admin/restaurants/[id]">> = Specific
  const handler = {} as typeof import("../../../app/api/super-admin/restaurants/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/super-admin/restaurants/[id]/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/super-admin/restaurants/[id]/status">> = Specific
  const handler = {} as typeof import("../../../app/api/super-admin/restaurants/[id]/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/super-admin/restaurants/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/super-admin/restaurants">> = Specific
  const handler = {} as typeof import("../../../app/api/super-admin/restaurants/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/upload">> = Specific
  const handler = {} as typeof import("../../../app/api/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/auth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/auth/callback">> = Specific
  const handler = {} as typeof import("../../../app/auth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/portal/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/portal">> = Specific
  const handler = {} as typeof import("../../../app/portal/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/[restaurantCode]/admin/inventory/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[restaurantCode]/admin/inventory">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/inventory/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[restaurantCode]/admin">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/customer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[restaurantCode]/customer">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/customer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/kds/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[restaurantCode]/kds">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/kds/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/[restaurantCode]/waiter/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/[restaurantCode]/waiter">> = Specific
  const handler = {} as typeof import("../../../app/[restaurantCode]/waiter/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/super-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/super-admin">> = Specific
  const handler = {} as typeof import("../../../app/super-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
